//import the fonts the metadeta and global css for tailwind
import { Comfortaa } from "next/font/google"
import type { Metadata } from "next";
import "./globals.css";

//add the google font
const comfortaa = Comfortaa({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-comfortaa",
});

//Export the metadeta for the application
export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by the weather app",
};

//Export the default function and render the parent root layout
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${comfortaa.variable}`}
    >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
      className="relative bg-[url(/images/background-clouds.jpg)] font-comfortaa font-extrabold text-white bg-no-repeat bg-center min-h-screen bg-cover" >
      <div className="absolute inset-0 bg-black/70"></div>
      <div className="relative z-10 h-full">
        {children}
      </div>
      </body>
    </html>
  );
}
